% This script plots a 2d view of the morphometrics of the study area using
% the lat/lon values associated with each point and saves the output as a
% .png file in the appropriate folder
%
% Michael Itzkin, 5/1/2018
%------------------------------------------------------------------------%
sand = [0.93, 0.79, 0.69];
water = [0.51, 0.90, 0.85];
fence_toe_color = [0.55 0.57 0.67];
fence_crest_color = [0.91, 0.41, 0.17];
fence_heel_color = [0.50, 0.00, 0.90];

Title = sprintf('2D View of %s %s', location(1:end-1), year);
latlon_figure = figure('name', Title);

hold on
grid on
box on

scatter(morpho_table(:,34), morpho_table(:,35),...
    'MarkerFaceColor', 'y',...
    'MarkerEdgeColor', 'k',...
    'DisplayName', 'MHW')
scatter(morpho_table(:,36), morpho_table(:,37),...
    'MarkerFaceColor', fence_toe_color,...
    'MarkerEdgeColor', 'k',...
    'DisplayName', 'Fenced Dune Toe')
scatter(morpho_table(:,38), morpho_table(:,39),...
    'MarkerFaceColor', 'r',...
    'MarkerEdgeColor', 'k',...
    'DisplayName', 'Fence')
scatter(morpho_table(:,40), morpho_table(:,41),...
    'MarkerFaceColor', fence_crest_color,...
    'MarkerEdgeColor', 'k',...
    'DisplayName', 'Fenced Dune Crest')
scatter(morpho_table(:,44), morpho_table(:,45),...
    'MarkerFaceColor', 'b',...
    'MarkerEdgeColor', 'k',...
    'DisplayName', 'Toe')
scatter(morpho_table(:,42), morpho_table(:,43),...
    'MarkerFaceColor', fence_heel_color,...
    'MarkerEdgeColor', 'k',...
    'DisplayName', 'Fenced Dune Heel')
scatter(morpho_table(:,46), morpho_table(:,47),...
    'MarkerFaceColor', 'm',...
    'MarkerEdgeColor', 'k',...
    'DisplayName', 'Crest')
scatter(morpho_table(:,48), morpho_table(:,49),...
    'MarkerFaceColor', 'g',...
    'MarkerEdgeColor', 'k',...
    'DisplayName', 'Heel')

legend('Location', 'northeastoutside')

set(gca, 'FontWeight', 'bold')
xlabel('Longitude (^{o})')
ylabel('Latitude (^{o})')
title(Title)

save_name = sprintf('%s%s%s%s%s.png', location(1:end-1), filesep, year, filesep, Title);
saveas(latlon_figure, save_name, 'png')
close()

