% Plot the profile for the profileReview.m function
%
% Michael Itzkin, 4/11/2019
%-----------------------------------------------------------------------%

hold on

% Plot the profile
h = plot(x_values, profiles(:, k, 3), 'Color', 'k', 'LineWidth', 2);
area([x_values(1) x_values(end)], [0.34 0.34], 'FaceColor',[0.51, 0.90, 0.85]);
area(x_values, profiles(:, k, 3), 'FaceColor', [0.93, 0.79, 0.69]);

% Add MHW
mhwPoint = scatter(useMorpho(k, 2), useMorpho(k, 3),...
    'MarkerFaceColor', 'y',...
    'MarkerEdgeColor', 'k',...
    'DisplayName', 'MHW');

% Add the berm
bermPoint = scatter(useMorpho(k, 60), useMorpho(k, 61),...
    'MarkerFaceColor', 'c',...
    'MarkerEdgeColor', 'k',...
    'DisplayName', 'Berm');

% Add the 2m contour
twoMeterPoint = scatter(useMorpho(k, 72), useMorpho(k, 73),...
    'MarkerFaceColor', [0.25, 0.80, 0.60],...
    'MarkerEdgeColor', 'k',...
    'DisplayName', '2m Contour');

% Add the natural dune toe
toePoint = scatter(useMorpho(k, 12), useMorpho(k, 13),...
    'MarkerFaceColor', 'b',...
    'MarkerEdgeColor', 'k',...
    'DisplayName', 'Toe');

% Add the natural dune crest
crestPoint = scatter(useMorpho(k, 14), useMorpho(k, 15),...
    'MarkerFaceColor', 'm',...
    'MarkerEdgeColor', 'k',...
    'DisplayName', 'Crest');

% Add the natural dune heel
heelPoint = scatter(useMorpho(k, 16), useMorpho(k, 17),...
    'MarkerFaceColor', 'g',...
    'MarkerEdgeColor', 'k',...
    'DisplayName', 'Heel');

% Add the fence
fencePoint = scatter(useMorpho(k, 6), useMorpho(k, 7),...
    'MarkerFaceColor', 'r',...
    'MarkerEdgeColor', 'k',...
    'DisplayName', 'Fence');

% Add the fenced dune toe
fenceToePoint = scatter(useMorpho(k, 4), useMorpho(k, 5),...
    'MarkerFaceColor', [0.55 0.57 0.67],...
    'MarkerEdgeColor', 'k',...
    'DisplayName', 'Fenced Dune Toe');

% Add the fenced dune crest
fenceCrestPoint = scatter(useMorpho(k, 8), useMorpho(k, 9),...
    'MarkerFaceColor', [0.91, 0.41, 0.17],...
    'MarkerEdgeColor', 'k',...
    'DisplayName', 'Fenced Dune Crest');

% Add the fenced dune heel
fenceHeelPoint = scatter(useMorpho(k, 10), useMorpho(k, 11),...
    'MarkerFaceColor', [0.50, 0.00, 0.90],...
    'MarkerEdgeColor', 'k',...
    'DisplayName', 'Fenced Dune Heel');

axHan.HitTest = 'off';
axHan.XDir = 'reverse';
axHan.Title.String = sprintf('%s%s, Profile %s of %s',...
    location, num2str(year), num2str(k), num2str(length(profiles(1, :, 1))));
axHan.YLim = [0 12];
grid on
hold off
