% This script creates a .csv file and a .mat file with the morphometrics
% data for the current study area. Also saves the x_values vector as a .mat
% file.
%
% Michael Itzkin, 5/1/2018
%------------------------------------------------------------------------%

% Save the local_x_values as a .mat file
save_x_name = sprintf('%s%s%s%sLocal X Values for %s %s.mat',...
    location(1:end-1), filesep, year, filesep, location(1:end-1), year);
save(save_x_name, 'local_x_values', '-mat')

% Set the filename to save as (both a .mat and .csv version)
save_morpho_name = sprintf('%s%s%s%sMorphometrics for %s %s.mat',...
    location(1:end-1), filesep, year, filesep, location(1:end-1), year);
save_morpho_csv_name = sprintf('%s%s%s%sMorphometrics for %s %s.csv',...
    location(1:end-1), filesep, year, filesep, location(1:end-1), year);

% Save the .mat file
save(save_morpho_name, 'morpho_table', '-mat')

% Create a cell array to use as the header for the .csv file
morpho_header = {'Profile No.', 'x_mhw', 'y_mhw', 'x_fence_toe',...
    'y_fence_toe', 'x_fence', 'y_fence', 'x_fence_crest', 'y_fence_crest',...
    'x_fence_heel', 'y_fence_heel', 'x_toe', 'y_toe', 'x_crest', 'y_crest',...
    'x_heel', 'y_heel', 'local_x_mhw', 'local_y_mhw', 'local_x_fence_toe',...
    'local_y_fence_toe', 'local_x_fence', 'local_y_fence',...
    'local_x_fence_crest', 'local_y_fence_crest', 'local_x_fence_heel',...
    'local_y_fence_heel', 'local_x_toe', 'local_y_toe', 'local_x_crest',...
    'local_y_crest', 'local_x_heel', 'local_y_heel', 'mhw_lon', 'mhw_lat',...
    'fence_toe_lon', 'fence_toe_lat', 'fence_lon', 'fence_lat',...
    'fence_crest_lon', 'fence_crest_lat', 'fence_heel_lon', 'fence_heel_lat',...
    'toe_lon', 'toe_lat', 'crest_lon', 'crest_lat', 'heel_lon', 'heel_lat'...
    'Natural Dune Volume', 'Fenced Dune Volume', 'Total Dune Volume',...
    'Beach Width', 'Start Crest Height', 'Start Crest Index',...
    'Start Fence Crest Height', 'Start Fence Crest Index', 'Beach Slope',...
    'Foreshore Slope', 'x_berm', 'y_berm', 'local_x_berm',...
    'local_y_berm', 'berm_lon', 'berm_lat'};

% Create the .csv file
fid = fopen(save_morpho_csv_name, 'w+'); 

% write header
for i = 1:length(morpho_header)
    fprintf(fid, '%s', morpho_header{i});
    if i ~= length(morpho_header)
        fprintf(fid, ',');
    else
        fprintf(fid, '\n' );
    end
end
% close file
fclose(fid);

% Append the data to the .csv file which should now have a header in the
% first row
dlmwrite(save_morpho_csv_name,...
    morpho_table,...
    '-append',...
    'Delimiter', ',',...
    'Precision', 9)


